### ISSUE TITLE
Update called on Front End

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson-Update-Extension#4]
Hello,
I extended the `FW_Extension_Update` as in `FW_Extension_Github_Update` example.
I noticed errors that are thrown in my overwritten functions appear sometimes on the front end.
This made me debug and I found out that for example `_get_theme_latest_version()` is being called even when calling frontend. Shouldn't this be limited to the backend (dashboard) calls only ?

**Comment by toleabivol** [comment]
Here is the `nex/framework-customizations/extensions/update/extensions/nex-update/class-fw-extension-nex-update.php`

https://gist.github.com/toleabivol/0322558cc4615ebeae9518f4030b7d1e

**Comment by toleabivol** [comment]
I added `if(!is_admin())return false;` to `_get_theme_latest_version()` and `_download_theme` but I think this should be also done inside the Service class that is being extended.

**Comment by ViorelEremia** [comment]
Unyson is build in this way every _init function from extensions is always called in both cases admin or not  if you check file ```framework/extensions/update/class-fw-extension-update.php``` function _init you see that it doesn't execute any code just add filters that are called by wordpress depending on environment admin or not.
So I think you were logged in when you saw those errors that is fine because you have this permission as admin ```! current_user_can( 'update_plugins' )```
